"""Verify Excel output is a valid ZIP and contains expected sheets.

These tests are skipped if the output file doesn't exist (requires
running generate_rediq_workbook.py first). They verify structural
integrity without loading openpyxl (fast, no format parsing needed).
"""
import json
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "output"

FOREST_HILLS_OUTPUT = OUTPUT_DIR / "Forest Hills Apartments_model.xlsm"
FOREST_HILLS_INPUTS = OUTPUT_DIR / "Forest Hills Apartments_model_inputs.json"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _zip_names(path: Path) -> list[str]:
    with zipfile.ZipFile(path) as zf:
        return zf.namelist()


# ---------------------------------------------------------------------------
# Forest Hills output — generated by the pipeline
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not FOREST_HILLS_OUTPUT.exists(), reason="No output file; run generate_rediq_workbook.py first")
class TestForestHillsExcelOutput:
    def test_output_is_valid_zip(self):
        """File must be a valid ZIP (Excel uses ZIP internally)."""
        with zipfile.ZipFile(FOREST_HILLS_OUTPUT) as zf:
            names = zf.namelist()
        assert len(names) > 0

    def test_output_has_workbook_xml(self):
        names = _zip_names(FOREST_HILLS_OUTPUT)
        assert "xl/workbook.xml" in names, "Missing xl/workbook.xml"

    def test_output_has_worksheets(self):
        names = _zip_names(FOREST_HILLS_OUTPUT)
        sheets = [n for n in names if n.startswith("xl/worksheets/sheet")]
        assert len(sheets) >= 3, f"Expected >=3 sheets, got {len(sheets)}: {sheets}"

    def test_output_has_content_types(self):
        """[Content_Types].xml is required in any valid OOXML file."""
        names = _zip_names(FOREST_HILLS_OUTPUT)
        assert "[Content_Types].xml" in names

    def test_output_has_styles(self):
        names = _zip_names(FOREST_HILLS_OUTPUT)
        assert "xl/styles.xml" in names

    def test_output_file_size_reasonable(self):
        """File should be at least 50KB — empty templates are ~10KB."""
        size_kb = FOREST_HILLS_OUTPUT.stat().st_size / 1024
        assert size_kb >= 50, f"Output is only {size_kb:.1f}KB — may be empty"


# ---------------------------------------------------------------------------
# --from-json path: run engine directly on inputs JSON and generate workbook
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not FOREST_HILLS_INPUTS.exists(), reason="No inputs JSON")
class TestFromJsonPipeline:
    def test_inputs_json_is_valid(self):
        """Inputs JSON must parse and have required canonical schema fields."""
        with open(FOREST_HILLS_INPUTS) as f:
            data = json.load(f)
        assert "schema_version" in data
        assert "unit_cohorts" in data
        assert "renovation_programs" in data
        assert isinstance(data["unit_cohorts"], list)
        assert len(data["unit_cohorts"]) > 0

    def test_inputs_json_has_renovation_programs(self):
        with open(FOREST_HILLS_INPUTS) as f:
            data = json.load(f)
        programs = data.get("renovation_programs", [])
        assert len(programs) > 0, "Expected renovation programs in inputs"
        # Check first program has required fields
        prog = programs[0]
        required = {"program_id", "target_cohort", "renovation_cost_per_unit",
                    "rent_premium_monthly", "strategy"}
        assert required <= prog.keys(), f"Missing: {required - prog.keys()}"

    def test_engine_runs_on_inputs_json(self):
        """Engine must produce metrics from the saved inputs JSON."""
        from engine.engine import run_underwriting
        with open(FOREST_HILLS_INPUTS) as f:
            inputs = json.load(f)
        results = run_underwriting(inputs)
        assert "metrics" in results
        assert "irr" in results["metrics"]
        irr = results["metrics"]["irr"]
        assert irr.get("levered_irr") is not None
        assert irr["levered_irr"] > 0
