"""
Tests for API Layer

Uses real deal data from output/ directory (generated by batch_process.py).
"""
import json
import unittest
from pathlib import Path

from engine.api import (
    handle_market_context,
    handle_portfolio_summary,
    handle_refi_vs_sell,
    handle_run_deal,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "output"


def _load_real_inputs():
    """Load real validated inputs from output directory."""
    # Try to find any *_inputs.json
    for f in sorted(OUTPUT_DIR.glob("*_inputs.json")):
        return json.loads(f.read_text(encoding="utf-8"))
    return None


def _load_real_results():
    """Load real engine results from output directory."""
    for f in sorted(OUTPUT_DIR.glob("*_outputs.json")):
        return json.loads(f.read_text(encoding="utf-8"))
    return None


class TestHandleRunDeal(unittest.TestCase):
    def test_success_with_inputs(self):
        inputs = _load_real_inputs()
        if not inputs:
            self.skipTest("No deal data in output/")
        result = handle_run_deal({"inputs": inputs})
        self.assertEqual(result["status"], "success")
        self.assertIn("metrics", result)
        self.assertIn("levered_irr", result["metrics"])

    def test_missing_inputs_returns_error(self):
        result = handle_run_deal({})
        self.assertEqual(result["status"], "error")
        self.assertIn("required", result["error"])

    def test_with_scenarios(self):
        inputs = _load_real_inputs()
        if not inputs:
            self.skipTest("No deal data in output/")
        result = handle_run_deal({
            "inputs": inputs,
            "options": {"scenarios": True, "scenario_type": "stabilized"},
        })
        self.assertEqual(result["status"], "success")
        self.assertIn("scenario_comparison", result)
        self.assertIn("bull", result["scenario_comparison"])
        self.assertIn("base", result["scenario_comparison"])
        self.assertIn("bear", result["scenario_comparison"])

    def test_with_include_cashflow(self):
        inputs = _load_real_inputs()
        if not inputs:
            self.skipTest("No deal data in output/")
        result = handle_run_deal({
            "inputs": inputs,
            "options": {"include_cashflow": True},
        })
        self.assertEqual(result["status"], "success")
        self.assertIn("cashflow", result)
        self.assertIn("by_year", result["cashflow"])

    def test_elapsed_seconds_included(self):
        inputs = _load_real_inputs()
        if not inputs:
            self.skipTest("No deal data in output/")
        result = handle_run_deal({"inputs": inputs})
        self.assertIn("elapsed_seconds", result)
        self.assertGreater(result["elapsed_seconds"], 0)


class TestHandlePortfolioSummary(unittest.TestCase):
    def test_from_directory(self):
        if not OUTPUT_DIR.exists():
            self.skipTest("No output directory available")
        result = handle_portfolio_summary({"directory": str(OUTPUT_DIR)})
        if result.get("summary", {}).get("deal_count", 0) == 0:
            self.skipTest("No deals in output directory")
        self.assertEqual(result["status"], "success")
        self.assertIn("summary", result)
        self.assertIn("by_metro", result)
        self.assertIn("deals", result)

    def test_from_inline_deals(self):
        inputs = _load_real_inputs()
        results = _load_real_results()
        if not inputs or not results:
            self.skipTest("No deal data in output/")
        result = handle_portfolio_summary({
            "deals": [{"inputs": inputs, "results": results}]
        })
        self.assertEqual(result["status"], "success")
        self.assertEqual(result["summary"]["deal_count"], 1)

    def test_missing_source_returns_error(self):
        result = handle_portfolio_summary({})
        self.assertEqual(result["status"], "error")


class TestHandleRefiVsSell(unittest.TestCase):
    def test_basic_comparison(self):
        inputs = _load_real_inputs()
        if not inputs:
            self.skipTest("No deal data in output/")
        result = handle_refi_vs_sell({
            "inputs": inputs,
            "refi_year": 3,
            "sell_year": 5,
            "refi_loan_terms": {
                "commitment": 800000,
                "rate": 0.055,
                "amort_years": 30,
                "io_months": 12,
                "loan_start_month": "2028-01",
            },
        })
        self.assertEqual(result["status"], "success")
        self.assertIn("comparison", result)
        self.assertIn("sell", result["comparison"])
        self.assertIn("refi_hold", result["comparison"])
        self.assertIn("delta", result["comparison"])

    def test_missing_inputs_returns_error(self):
        result = handle_refi_vs_sell({})
        self.assertEqual(result["status"], "error")


if __name__ == "__main__":
    unittest.main()
